m4_include(config/armci.m4)
m4_include(config/mpicc.m4)
m4_include(config/mpicxx.m4)
m4_include(config/cell.m4)
m4_include(config/ofed.m4)
m4_include(config/gm.m4)
m4_include(config/mx.m4)
m4_include(config/sisci.m4)
m4_include(config/vapi.m4)
m4_include(config/hrtimer.m4)
m4_include(config/check_module.m4)
m4_include(config/check_pattern.m4)
m4_include(config/cpuaffinity.m4)

